FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /app
COPY BlazorDigitalOcean.csproj BlazorDigitalOcean.csproj
RUN dotnet restore BlazorDigitalOcean.csproj
COPY . .
RUN dotnet publish -c Release -o /output --no-restore --nologo